apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP # ou LoadBalancer ou NodePort (pouco utilizado) ou ExternalName (outro arquivo)
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
